# This is the configuration file for the plugin.
door:

  # Door open setting
  # if true, allow everyone to enter the server, except for players on the ban list
  # if false, allow the player in the allowlist to come into the server.
  open: false

  # The available characters for the verification code
  # The length requires to be 10 or more
  available_characters: "abcdefghijklmnopqrstuvwxyz0123456789"

  # The length of the verification code
  # The length requires to be 4 or more
  code_length: 6

  # The expiration time of the verification code
  # 0 means the verification code will never expire
  expire_day: 14

  # Database setting
  database:
      # The database type, currently only support sqlite
      type: sqlite
